### ISSUE TITLE
Quality setting alongside AVIF / JXL has no effect

### ISSUE THREAD

**Issue by gloscombe-amp** [blocknotes/magickwand-crystal#3]
Using Imagemagick 7.1.1 (latest in Fedora 38) and 0.3 of this lib

Convert an image (jpg) to webp quality 10 and 90, the filesize is as expected, eg
51K Jun 14 15:22 test_10.webp
284K Jun 14 15:22 test_90.webp

However, repeat the same test with AVIF
91K Jun 14 15:22 test_10.avif
91K Jun 14 15:22 test_90.avif

If I use magick convert <input> <output>.avif - I get the same 91k, so looks like the quality is getting dropped and using the default.

**Comment by blocknotes** [comment]
This component simply bind the underlying functions so it looks an issue with MagickWand library
